### ISSUE TITLE
Messages are duplicated in app

### ISSUE THREAD

**Issue by mohgh** [tinode/tindroid#26]
Sometimes messages (both texts and photos) will come twice after each other in the messages list. There's only one copy in the remote database but they get duplicated on the client side. I couldn't reproduce this bug but it happens sometimes. Can you guide me in the direction to fix this issue? Maybe there are two pathways to insert in the local database? Thank you in advance.

**Comment by mohgh** [comment]
After I investigate more I realized the root of the problem by debugging the application. It's highly likely that there are multiple parallel WebSocket connections that each one of them receives data from the server and both of them try to render the result on the screen by calling `msgReceived` function in `Storage` class. Is there a way to prevent this issue?

**Comment by or-else** [comment]
Are you using a stock app or a modified one? If a modified one make sure you sent noecho=true when sending messages. Otherwise you will get a second copy of the message.

I would suggest adding a check before inserting the message into the db. Somewhere here
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/db/MessageDb.java#L126

The message has a unique combination of topicId + seqId. If a message with the same combination already exists you will be able to catch the second insertion.

**Comment by mohgh** [comment]
I'm modifying the original version of the app. I've search in the code and noecho is always true. I've logged topicId and seq in the method you mentioned but they are always different. Yet some photos are duplicated. Is it possible that there is only on copy in the remote db but it has different seqs in app on time of receiving?

**Comment by or-else** [comment]
Also, look at logcat at the time of duplication. See if anything is there. Copy the relevant part here.

**Comment by mohgh** [comment]
When both users are attached to the topic in the application there's no duplication but when one user is not in the application for a while and another user sends a photo to him, it gets duplicated in the client. 
I'm sure that sever sends one message twice in these situations. I will provide the logcat output when I get home.

**Comment by or-else** [comment]
It could send the same message twice, once per user. But the messages are identical, including seqId. They are stored in the DB under different topicId (each topic may be stored multiple times, once per user), so if the accounts are switched correctly when switching users you should not see any duplication.

Here is how topic is stored:
```java
    static final String CREATE_TABLE =
            "CREATE TABLE " + TABLE_NAME + " (" +
                    _ID + " INTEGER PRIMARY KEY," +
                    COLUMN_NAME_ACCOUNT_ID
                    + " REFERENCES " + AccountDb.TABLE_NAME + "(" + AccountDb._ID + ")," +
                    COLUMN_NAME_STATUS + " INT," +
                    COLUMN_NAME_TOPIC + " TEXT," + ...
```
With a unique index on COLUMN_NAME_ACCOUNT_ID + COLUMN_NAME_TOPIC. Then messages reference topicId as a foreign key, which is dependent on accountId.

**Comment by mohgh** [comment]
Sorry for the delayed response. I investigated more carefully and I can confirm that the problem is on the server side rather than the client. 
This is the scenario of the events. Carol has logged in on one device and Bob has logged in on another device. The app is closed on Bob's device but the device is connected to the internet. Carol sends a photo to Bob. The message status has changed to received. On Bob's device, two notification has received. When Bob opens the app there are two duplicated messages present in the topic for Carol. 
These messages have different seqIds and both are present in the remote database. Here are the message objects from the database.
```
{
"Content": {
"ent": [
{
"data": {
"height": 1080 ,
"mime":  "image/jpeg" ,
"name":  "IMG-20181211-WA0000.jpg" ,
"val": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICU........." ,
"width": 607
} ,
"tp":  "IM"
}
] ,
"fmt": [
{
"at": 0 ,
"key": 0 ,
"len": 1
}
] ,
"txt":  " "
} ,
"CreatedAt": Thu Dec 13 2018 19:54:35 GMT+00:00 ,
"From":  "1ayZUemA8Ks" ,
"Head": {
"mime":  "text/x-drafty"
} ,
"Id":  "-nrv1nKGfbE" ,
"SeqId": 19 ,
"Topic":  "p2phP3DDpxrQDrVrJlR6YDwqw" ,
"UpdatedAt": Thu Dec 13 2018 19:54:35 GMT+00:00
}
```

```
{
"Content": {
"ent": [
{
"data": {
"height": 1080 ,
"mime":  "image/jpeg" ,
"name":  "IMG-20181211-WA0000.jpg" ,
"val": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICU........." ,
"width": 607
} ,
"tp":  "IM"
}
] ,
"fmt": [
{
"at": 0 ,
"key": 0 ,
"len": 1
}
] ,
"txt":  " "
} ,
"CreatedAt": Thu Dec 13 2018 19:54:36 GMT+00:00 ,
"From":  "1ayZUemA8Ks" ,
"Head": {
"mime":  "text/x-drafty"
} ,
"Id":  "e-IDcBiLgMM" ,
"SeqId": 20 ,
"Topic":  "p2phP3DDpxrQDrVrJlR6YDwqw" ,
"UpdatedAt": Thu Dec 13 2018 19:54:36 GMT+00:00
}
```

**Comment by or-else** [comment]
Does it happen with messages with attachments only? If yes, I think I know where the bug is.

Here is what I think is happening.

1. User starts drafting a message with an attachment in topic. The user's session is subscribed to topic  at this time.
2. When you click the attachment button, a file chooser activity is started. The Tinode MessageActivity goes into background and it causes it to unsubscribe from the topic (it sends a {leave} message).
3. The message is completed and saved to DB. Because the topic is unsubscribed in step 2 the message cannot be immediately sent.
4. The Message Activity is resumed and it re-subscribes to the topic. Once subscribed, MessageActivity launches a thread to send queued unsent messages. That's when the first copy of the message is sent. 
5. And now something else sends the second copy of the message.

**Comment by mohgh** [comment]
I think if MessagesFragment keeps the ids of messages it sending and avoid syncing one message twice by checking the in-memory ids, the problem will resolve. I have added this peace of code in onLoadFinished:

```
public void onLoadFinished(@NonNull Loader<UploadResult> loader, final UploadResult data) {
        final FragmentActivity activity = getActivity();
        if (activity != null) {
            // Kill the loader otherwise it will keep uploading the same file whenever the activity
            // is created.
            activity.getSupportLoaderManager().destroyLoader(loader.getId());
        }

        // Avoid processing the same result twice;
        if (data.processed) {
            return;
        } else {
            data.processed = true;
        }

        **if (processingIds.contains(data.msgId)){
            return;
        }**

        if (data.msgId > 0) {
            **processingIds.add(data.msgId);**
            try {
                mTopic.syncOne(data.msgId).thenApply(new PromisedReply.SuccessListener<ServerMessage>() {
                    @Override
                    public PromisedReply<ServerMessage> onSuccess(ServerMessage result) {
                        if (activity != null && result != null) {
                            // Log.d(TAG, "onLoadFinished - onSuccess " + result.ctrl.id);
                            processingIds.remove(data.msgId);
                            activity.runOnUiThread(new Runnable() {
                                   @Override
                                   public void run() {
                                       int pos = findItemPositionById(data.msgId);
                                       if (pos >= 0) {
                                           runMessagesLoader();
                                       }
                                   }
                               }
                            );
                        }
                        return null;
                    }
                }, null);
            } catch (Exception ex) {
                Log.d(TAG, "Failed to sync", ex);
                Toast.makeText(activity, R.string.failed_to_send_message, Toast.LENGTH_LONG).show();
            }
        } else if (data.error != null) {
            runMessagesLoader();
            Toast.makeText(activity, data.error, Toast.LENGTH_LONG).show();
        }
    }
```

**Comment by or-else** [comment]
I think a better solution would be to create only a single place where messages are sent from. There are currently two such places.

**Comment by mohgh** [comment]
Could you show me where are these places? The method `syncOne` is only called in `onLoadFinished` method.

**Comment by mohgh** [comment]
Thank you very much. The problem was sending one message on syncAll methods and also in syncOne method. I fixed it by putting two arrays in MessagesActiviy and keeping track of messages that are drafted but not synced yet. I think this solution is very messy and not worths merging with base code. Please let me know if you have the time to fix this issue by restructuring the code to send the message only in one place.

**Comment by or-else** [comment]
I'll look into it.

**Comment by or-else** [comment]
Fix pushed: https://github.com/tinode/tindroid/commit/83a2f88f9902b9996fa0fe29176174aacf5622e2

**Comment by mohgh** [comment]
I've changed my code as you've changed in the mentioned commit but the error persists. You can check it yourself. Login as bob and send carol 5+ images (not as file). Then login as carol and you will see some of these images are duplicated.

**Comment by or-else** [comment]
OK, I'll do a bit more testing. Thanks.

**Comment by or-else** [comment]
I've done a lot more testing after making 01afb88. I no longer see duplication.

**Comment by mohgh** [comment]
I've tested the new version. The bug is fixed. Thank you.

**Comment by mohgh** [comment]
Dear @or-else 
I'm experiencing this bug again.
Has something changed that makes this bug reappear?
Sometimes messages are duplicated. Both text and images.

**Comment by or-else** [comment]
Could you please create a new issue instead of reopening this one.
